plugins {
    id "com.android.application"
    id "com.chaquo.python"
}

android {
    namespace "io.apex.standalone"
    compileSdk 34

    defaultConfig {
        applicationId "io.apex.standalone"
        minSdk 24
        targetSdk 34
        versionCode 3
        versionName "0.3.0"

        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a"
        }

        python {
            version "3.10"
            buildPython "python3"
            pip {
                install "androguard==4.1.4"
                install "jinja2>=3.1.0"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

python {
    srcDir "../../../"
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.7.0"
}
