#!/usr/bin/env bash
# Regenerate Python lockfiles from declared minimum versions.
# Usage: bash scripts/generate_lockfiles.sh
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

header() {
  local title="$1"
  cat <<EOF
# ${title}
# Generated by scripts/generate_lockfiles.sh — do not edit by hand.
# Regenerate: bash scripts/generate_lockfiles.sh
#
EOF
}

echo "==> requirements.lock (runtime)"
python3 -m venv "$TMP/prod"
"$TMP/prod/bin/pip" install -q -U pip wheel
"$TMP/prod/bin/pip" install -q 'androguard>=4.1.4' 'jinja2>=3.1.0'
{
  header "APEX runtime lockfile"
  "$TMP/prod/bin/pip" freeze | grep -vE '^(pip|setuptools|wheel)==' | sort -f
} > requirements.lock

echo "==> requirements-dev.lock (runtime + dev/mcp)"
python3 -m venv "$TMP/dev"
"$TMP/dev/bin/pip" install -q -U pip wheel
"$TMP/dev/bin/pip" install -q \
  'androguard>=4.1.4' 'jinja2>=3.1.0' \
  'pytest>=8.0' 'pytest-benchmark>=4.0' 'ruff>=0.16.1' 'fastmcp>=2.0'
{
  header "APEX runtime + dev/mcp lockfile"
  "$TMP/dev/bin/pip" freeze | grep -vE '^(pip|setuptools|wheel)==' | sort -f
} > requirements-dev.lock

echo "==> Cargo.lock (workspace)"
if command -v cargo >/dev/null 2>&1; then
  cargo generate-lockfile
else
  echo "cargo not found — left Cargo.lock unchanged" >&2
fi

echo "Done."
wc -l requirements.lock requirements-dev.lock Cargo.lock
